### ISSUE TITLE
Segfault on Leukemia example

### ISSUE THREAD

**Issue by TisserantG** [Artelnics/OpenNN#15]
Hello,
I try to test the leukemia example, and I have errors : 
Program received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:268
268		vmovdqu	0x60(%rsi), %ymm3

I use bt on gdb, and I have this stack :

#0  __memmove_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:268
#1  0x000000000061103f in double* std::__copy_move<true, true, std::random_access_iterator_tag>::__copy_m<double>(double const*, double const*, double*) ()
#2  0x000000000060f9ba in double* std::__copy_move_a<true, double*, double*>(double*, double*, double*)
    ()
#3  0x00000000006794ab in __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > std::__copy_move_a2<true, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > >(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >) ()
#4  0x00000000006792b9 in __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > std::move<__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > >(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >) ()
#5  0x00000000006791b2 in std::vector<double, std::allocator<double> >::_M_erase(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >) ()
#6  0x0000000000678f10 in std::vector<double, std::allocator<double> >::erase(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >) ()
#7  0x0000000000777012 in OpenNN::Perceptron::prune_input(unsigned long const&) ()
#8  0x0000000000771115 in OpenNN::PerceptronLayer::prune_input(unsigned long const&) ()
#9  0x0000000000659772 in OpenNN::MultilayerPerceptron::prune_input(unsigned long const&) ()
#10 0x0000000000642ec7 in OpenNN::NeuralNetwork::prune_input(unsigned long const&) ()
#11 0x0000000000725ce2 in OpenNN::InputsSelectionAlgorithm::set_neural_inputs(OpenNN::Vector<bool> const&) ()
---Type <return> to continue, or q <return> to quit---
#12 0x0000000000727d98 in OpenNN::InputsSelectionAlgorithm::perform_model_evaluation(OpenNN::Vector<bool> const&) ()
#13 0x000000000072bf2d in OpenNN::GrowingInputs::perform_inputs_selection() ()
#14 0x000000000070d3e0 in OpenNN::ModelSelection::perform_inputs_selection() const ()
#15 0x00000000005ccdc5 in main ()

I build the program using make. 
I'm on Fedora 24 and my GCC version is 6.2.1 but the same problem on Ubuntu 16.10 and GCC 5.4.

**Comment by FernandoGomezP** [comment]
It was a failure in our creation of the neural network. It is solved in the new version of OpenNN.

**Comment by kommander** [comment]
```OpenNN test suite results:
Tests run: 2440
Tests passed: 2440
Tests failed: 0
Test OK
```
I can confirm this is not happening anymore.
